name: cppcheck-action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Cppcheck
      run: sudo apt -y install cppcheck
    - name: Run Cppcheck
      run: cppcheck 3_Implementation
